# Here you can specify default options for TinyMCE across all controllers
#
theme: advanced
theme_advanced_toolbar_location: top
theme_advanced_buttons1: 'undo,redo,cut,copy,paste,pastetext,|,bold,italic,strikethrough,blockquote,charmap,bullist,numlist,removeformat'
theme_advanced_buttons2: ''
theme_advanced_buttons3: ''
# plugins:
#  - table
#  - fullscreen
