# Here you can specify default options for TinyMCE across all controllers
#
width: 640
height: 480
theme: advanced
theme_advanced_toolbar_location: top
theme_advanced_buttons1: 'undo,redo,cut,copy,paste,pastetext,|,justifyleft,justifycenter,justifyright,justifyfull,|,bold,italic,strikethrough,blockquote,charmap,bullist,numlist,removeformat'
theme_advanced_buttons2: 'link,unlink,anchor,image,|,code,|, styleprops'
theme_advanced_buttons3: ''
plugins:
   - style
#  - table
#  - fullscreen
