development:
  public_host_username: git
  public_host: playground.tayandann.net
  public_port: 8888
  local_port: 3000
  server_alive_interval: 0

test:
  public_host_username: 
  public_host: 
  public_port: 4007
  local_port: 3000
  server_alive_interval: 0

production:
  public_host_username: 
  public_host: 
  public_port: 4007
  local_port: 3000
  server_alive_interval: 0