#!/usr/bin/env ruby
require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))

class MailerDaemonFetcherDaemon < Daemon::Base
  
  @config = YAML.load_file("#{Rails.root}/config/mailer_daemon.yml")
  @config = @config[Rails.env].to_options
  
  @sleep_time = @config.delete(:sleep_time) || 3600
  def self.start
    puts "Starting MailerDaemonFetcherDaemon"
    # Add your own receiver object below
    @fetcher = Fetcher.create({:receiver => EmailIncoming}.merge(@config))

    loop do
      @fetcher.fetch
      sleep(@sleep_time)
    end
  end
  
  def self.stop
    puts "Stopping MailerDaemonFetcherDaemon"
  end
  
end

MailerDaemonFetcherDaemon.daemonize
